title: JekyllChess
description: A theme for chess blogging with figurine notation, FEN diagrams, and a simple PGN viewer. Built on chess.js and chessboard.js libraries.
url: "https://jekyllrookpawn.github.io"
exclude:
- README.md
markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: https://github.com/henrythemes/jekyll-minimal-theme
# remote_theme: https://github.com/henrythemes/hello-jekyll-theme
